module.exports = {
  ingredients: [
    {
      id: 11,
      name: "cheese",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/cheese_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/cheese.svg",
      price: 3000,
      index: 1,
    },
    {
      id: 1,
      name: "peperoni",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/peperonis_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/peperoni.svg",
      price: 3000,
    },
    {
      id: 2,
      name: "tomatoes",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/Tomatoes_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/tomatoes.svg",
      price: 4000,
    },
    {
      id: 3,
      name: "jalapenos",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/Jalapenos_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/jalapenos.svg",
      price: 3000,
    },
    {
      id: 4,
      name: "mushrooms",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/Mushrooms_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/mushrooms.svg",
      price: 6000,
      index: 4,
    },
    {
      id: 5,
      name: "peppers",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/peppers_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/peppers.svg",
      price: 2000,
    },
    {
      id: 6,
      name: "onions",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/Onions_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/onion.svg",
      price: 1000,
      index: 2,
    },
    {
      id: 7,
      name: "bacon",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/Bacon_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/bacon.svg",
      price: 5000,
    },
    {
      id: 8,
      name: "houseSauce",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/swissCheese_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/swissCheese.svg",
      price: 3000,
    },
    {
      id: 9,
      name: "brocoli",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/brocoli_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/broccoli.svg",
      price: 7000,
    },
    {
      id: 10,
      name: "olives",
      image: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/olives_icon.svg",
      pizzaImage: "https://jogafiles.s3.us-east-2.amazonaws.com/pizzapp/olives.svg",
      price: 3000,
    },
  ],
  myPizzas: [
    {
      id: 1,
      name: "BBQ Pizza",
      ingredients: ["cheese", "peperoni", "tomatoes", "bacon", "houseSauce"],
      recipe: "Mozzarella, BBQ sauce, tomato, mushrooms, and olives.",
    },
    {
      id: 2,
      name: "PESTO VEGGIE PIZZA",
      ingredients: ["cheese", "peperoni", "tomatoes", "bacon", "houseSauce"],
      recipe: "Mozzarella, basil pesto sauce, and a blend of healthy veggies.",
    },
    {
      id: 3,
      name: "Margherita Pizza",
      ingredients: ["cheese", "peperoni", "tomatoes", "bacon", "houseSauce"],
      recipe: "Classic crust, Mozzarella, tomato Sauce, and double pepperoni.",
    },
  ],
  pizzas: [{}],
};
